# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MDM iOS Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MDM iOS Example
  pod 'MDMBundle', :path => '/Users/phelipelopes/Documents/github/test'
end

target 'MDMNotificationService' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    
    # Pods for NotificationPOC
    pod 'MDMNotification', :path => '/Users/phelipelopes/Documents/github/test'
    pod 'MDMCore', :path => '/Users/phelipelopes/Documents/github/test'
end

target 'MDMNotificationContent' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

    # Pods for NotificationPOC
    pod 'MDMNotification', :path => '/Users/phelipelopes/Documents/github/test'
    pod 'MDMCore', :path => '/Users/phelipelopes/Documents/github/test'
end

