# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'MDM iOS Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MDM iOS Example
  pod 'MDMBundle', '3.9.14'

end

target 'MDMNotificationService' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for NotificationPOC
    pod 'MDMCore', '3.9.14'
    pod 'MDMNotification', '3.9.14'
end

target 'MDMNotificationContent' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for NotificationPOC
    pod 'MDMCore', '3.9.14'
    pod 'MDMNotification', '3.9.14'
    
end
